# -*- coding: utf-8 -*-
"""svm_part2_kernels

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JOXa-69jAD6SxgaXzVNpllFeIOi4_7c5
"""

#Loading data on Google Colab:
#!wget user.ceng.metu.edu.tr/~artun/ceng499/hw3_files.zip
#!unzip hw3_files.zip

import numpy as np
import matplotlib.pyplot as plt


def draw_svm(clf, x, y, x1_min, x1_max, x2_min, x2_max, target=None):
    """
    Draws the decision boundary of an svm.
    :param clf: sklearn.svm.SVC classifier
    :param x: data Nx2
    :param y: label N
    :param x1_min: minimum value of the x-axis of the plot
    :param x1_max: maximum value of the x-axis of the plot
    :param x2_min: minimum value of the y-axis of the plot
    :param x2_max: maximum value of the y-axis of the plot
    :param target: if target is set to path, the plot is saved to that path
    :return: None
    """
    y = y.astype(bool)
    xx, yy = np.meshgrid(np.linspace(x1_min, x1_max, 500),
                         np.linspace(x2_min, x2_max, 500))
    z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()])
    z = z.reshape(xx.shape)
    disc_z = z > 0
    plt.clf()
    plt.imshow(disc_z, interpolation='nearest',
               extent=(xx.min(), xx.max(), yy.min(), yy.max()), aspect='auto',
               origin='lower', cmap=plt.cm.RdBu, alpha=.3)
    plt.contour(xx, yy, z, levels=[-1, 1], linewidths=2,
                linestyles='dashed', colors=['red', 'blue'], alpha=0.5)
    plt.contour(xx, yy, z, levels=[0], linewidths=2,
                linestyles='solid', colors='black', alpha=0.5)
    positives = x[y == 1]
    negatives = x[y == 0]
    plt.scatter(positives[:, 0], positives[:, 1], s=50, marker='o', color="none", edgecolor="black")
    plt.scatter(negatives[:, 0], negatives[:, 1], s=50, marker='s', color="none", edgecolor="black")
    sv_label = y[clf.support_]
    positive_sv = x[clf.support_][sv_label]
    negative_sv = x[clf.support_][~sv_label]
    plt.scatter(positive_sv[:, 0], positive_sv[:, 1], s=50, marker='o', color="white", edgecolor="black")
    plt.scatter(negative_sv[:, 0], negative_sv[:, 1], s=50, marker='s', color="white", edgecolor="black")
    plt.xlim(x1_min, x1_max)
    plt.ylim(x2_min, x2_max)
    plt.gca().set_aspect('equal', adjustable='box')
    if target is None:
        plt.show()
    else:
        plt.savefig(target)



import numpy as np
train_data = np.load ( "/content/hw3/hw3_data/nonlinsep/train_data.npy" )
train_labels = np.load ( "/content/hw3/hw3_data/nonlinsep/train_labels.npy" )


from sklearn.utils import shuffle
train_data,train_labels= shuffle(train_data,train_labels) #shuffle the data
from sklearn.svm import SVC

#kernels= linear, rbf, polynomial, sigmoid

#svclassifier = SVC(kernel='linear')
#svclassifier = SVC(kernel='poly')
#svclassifier = SVC(kernel='rbf')
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(train_data, train_labels)

x1_min=-3
x1_max =3
x2_min= -3
x2_max=3

draw_svm(svclassifier, train_data, train_labels, x1_min, x1_max, x2_min, x2_max, target=None)